
// Objective-C API for talking to the following Go packages
//
//	github.com/missuo/herdrm/tailcat/tailcatmobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Tailcat_FRAMEWORK_H__
#define __Tailcat_FRAMEWORK_H__

#include "Tailcatmobile.objc.h"
#include "Universe.objc.h"

#endif
